// Ts
import {
  Product,
  ProductCard,
  ProductsAds,
  ProductCategories,
} from '../models/product.interface';

export const AllProducts: Product[] = [
  {
    id: '1',
    title: 'Jordan 11 Retro Low IE White Gym Red',
    description_short:
      'Originally designed as a Michael Jordan player-exclusive sneaker for the 1996 season, the Jordan 11 Retro Low IE White Gym Red is an International Exclusive re-release of the offering.',
    description: [
      'This low-cut sneaker sports a white leather upper highlighted by Gym Red overlays. White mesh windows appear on the elephant print Gym Red overlays. Black hues on the tongue, Jumpman tongue branding, and sockliner provide a contrasting tone to the upper. Other details include parallel stitching on the leather upper, round laces, and a white tongue. A white midsole and a red translucent outsole with black herringbone-patterned traction inserts complete the design.',
      'What our experts love about this sneaker is its design and colorway. The white leather upper with Gym Red overlays and elephant print details on the wrap-around overlay makes this sneaker stand out. The Jordan 11 Retro Low IE White Gym Red was made available on September 23rd, 2017.',
    ],
    images: {
      local:
        '../../../../assets/image/products/Jordan 11 Retro Low IE White Gym Red.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Air-Jordan-11-Retro-Low-IE-White-Gym-Red/Images/Air-Jordan-11-Retro-Low-IE-White-Gym-Red/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1635281283&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '44.5',
      '45',
    ],
    tag: [
      { id: 1, name: 'jordan' },
      { id: 2, name: 'nike' },
    ],
    color: ['white', 'red'],
    releaseDate: new Date(),
    condition: 'new',
    review: 4,
    price: 170,
    discount: 5,
  },
  {
    id: '2',
    title: 'Jordan 11 Retro Low Midnight Navy',
    description_short:
      'The Air Jordan 11 Retro Low Midnight Navy is made by a midnight navy paired color palette along with a gum outsole.',
    description: [
      'This Low Air Jordan 11 model includes a ballistic mesh upper, which is reinforced with a shiny patent leather overlay, both finished in Midnight Navy hue. Cushioning arrives via a Phylon midsole, enhanced with a full-length AIR unit and supported by a rubber outsole with herringbone pattern pods for traction under the toe and heel.',
    ],
    images: {
      local:
        '../../../../assets/image/products/Jordan 11 Retro Low Midnight Navy.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Air-Jordan-11-Retro-Low-Midnight-Navy/Images/Air-Jordan-11-Retro-Low-Midnight-Navy/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1711049227&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
    ],
    tag: [
      { id: 1, name: 'jordan' },
      { id: 2, name: 'nike' },
      { id: 3, name: 'retro' },
    ],
    color: ['black', 'white'],
    releaseDate: new Date(),
    condition: 'new',
    review: 3.5,
    price: 274,
    discount: 3,
  },
  {
    id: '3',
    title: 'Jordan 11 Retro Platinum Tint',
    description_short: 'Platinum Tint',
    description: [
      'Jordan brand has dropped hit after hit and have finally gone platinum with the Jordan 11 Retro Platinum tint. This silhouette comes with an all sail upper with red accents, white midsole, and a sail sole.',
    ],
    images: {
      local:
        '../../../../assets/image/products/Jordan 11 Retro Platinum Tint.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Air-Jordan-11-Retro-Platinum-Tint/Images/Air-Jordan-11-Retro-Platinum-Tint/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1635271677&h=384&q=57',
    },
    size: [
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '44.5',
      '45',
      '46',
    ],
    tag: [
      { id: 1, name: 'jordan' },
      { id: 2, name: 'nike' },
      { id: 3, name: 'retro' },
    ],
    color: ['red', 'white'],
    releaseDate: new Date(),
    condition: 'new',
    review: 5,
    price: 288,
    discount: 45,
  },
  {
    id: '4',
    title: 'Jordan 11 Retro Pantone',
    description_short:
      'The Air Jordan 11 Retro Pantone made its market debut on December 23, 2014',
    description: [
      `The Retro Pantone Air Jordan 11 is a unique iteration of the iconic Air Jordan 11 silhouette. It showcases a predominantly Legend Blue color scheme, applied to both the patent leather and smooth leather upper. The shoe features a clean white midsole and a translucent outsole with a tint of Legend Blue. Originally unveiled as a sample collection during the 2010 World Basketball Festival, this particular colorway was later released as part of the "Ultimate Gift of Flight Pack" alongside a similarly styled Air Jordan 29. The'University Blue colorway pays homage to Michael Jordan's college days, when he achieved NCAA Championship success as a member of the University of North Carolina Tarheels`,
    ],
    images: {
      local: '../../../../assets/image/products/Jordan 11 Retro Pantone.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Air-Jordan-11-Retro-Pantone/Images/Air-Jordan-11-Retro-Pantone/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1690482609&h=384&q=57',
    },
    size: [
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '44.5',
      '45',
      '46',
    ],
    tag: [
      { id: 1, name: 'jordan' },
      { id: 2, name: 'nike' },
      { id: 3, name: 'retro' },
    ],
    color: ['blue', 'white'],
    releaseDate: new Date(),
    condition: 'new',
    review: 5,
    price: 266,
    discount: 25,
  },
  {
    id: '5',
    title: 'Nike Air Max 1 86 OG Big Bubble Air Max Day (2024)',
    description_short:
      'The Nike Air Max 1 86 OG Big Bubble Air Max Day (2024) is a special-edition sneaker that was released to celebrate Air Max Day.',
    description: [
      'The sneaker boasts a white mesh construction with suede overlays in Royal Blue and Sail. Unlike other Nike Air Max 1 models released as part of Air Max Day, the "Big Bubble Air Max Day" iteration features a Volt midsole that catches the eye',
      'The tongue’s inner lining also showcases a panel of Volt synthetic material. The oversized window in the heel displays visible Air Max units and four circular cut outs.',
    ],
    images: {
      local:
        "../../../../assets/image/products/Nike Air Max 1 '86 OG Big Bubble Air Max Day (2024).avif",
      number: 1,
      path: 'https://images.stockx.com/360/Nike-Air-Max-1-86-OG-Big-Bubble-Air-Max-Day-2024-Womens/Images/Nike-Air-Max-1-86-OG-Big-Bubble-Air-Max-Day-2024-Womens/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1711643088&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '44.5',
      '45',
    ],
    tag: [{ id: 2, name: 'nike' }],
    color: ['white', 'blue'],
    releaseDate: new Date(),
    condition: 'new',
    review: 2.5,
    price: 170,
    discount: 15,
  },
  {
    id: '6',
    title: 'Nike Air VaporMax 360 Varsity Royal',
    description_short: 'The Nike Air VaporMax 1 is a special-edition.',
    description: ['The sneaker that catches the eye'],
    images: {
      local: '../../../../assets/image/products/Nike Air VaporMax 360.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Nike-Air-Vapormax-360-Varsity-Royal/Images/Nike-Air-Vapormax-360-Varsity-Royal/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1635278810&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
    ],
    tag: [{ id: 2, name: 'nike' }],
    color: ['white', 'blue'],
    releaseDate: new Date(),
    condition: 'used',
    review: 3.5,
    price: 140,
    discount: 25,
  },
  {
    id: '7',
    title: 'Nike LeBron 4 Fruity Pebbles (2024)',
    description_short:
      'A vibrant and playful addition to the LeBron sneaker lineage. This edition bursts onto the scene with a colorway inspired by the iconic cereal.',
    description: [
      "The Nike LeBron 4 Fruity Pebbles 2024 features advanced cushioning and a foamposite shell upper to ensure optimal comfort. Its distinctive design, from the bold color palette to the intricate detailing, showcases Nike's commitment to innovative aesthetics. ",
      "If you're a sneakerhead or LeBron fan in search of a unique addition to your collection, this sneaker hits all the right notes.",
    ],
    images: {
      local:
        '../../../../assets/image/products/Nike LeBron 4 Fruity Pebbles (2024).avif',
      number: 1,
      path: 'https://images.stockx.com/360/Nike-LeBron-4-Fruity-Pebbles-2024/Images/Nike-LeBron-4-Fruity-Pebbles-2024/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1708542689&h=384&q=57',
    },
    size: [
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
    ],
    tag: [
      { id: 1, name: 'jordan' },
      { id: 2, name: 'nike' },
    ],
    color: ['red', 'white'],
    releaseDate: new Date(),
    condition: 'new',
    review: 1.5,
    price: 115,
    discount: 3,
  },
  {
    id: '8',
    title: 'Nike Air VaporMax 360 Black',
    description_short:
      'The Nike Air VaporMax 360 Black is a standalone sneaker model of the VaporMax collection by Nike.',
    description: [
      'The Black Nike Air VaporMax 360 features a predominantly black colorway with accents of Anthracite. The upper is designed with a TPU frame that provides structure and support, while its sole combines the Air Max 360 sole unit with the VaporMax sole technology. The sole unit is made up of several air pockets that run the length of the shoe, designed to absorb shock. The shoe has a lace-up closure system, as well as rubber outsoles that provide traction on a variety of surfaces.',
    ],
    images: {
      local: '../../../../assets/image/products/Nike_Air_VaporMax_360.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Nike-Air-VaporMax-360-Black/Images/Nike-Air-VaporMax-360-Black/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1634926789&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
    ],
    tag: [{ id: 2, name: 'nike' }],
    color: ['black'],
    releaseDate: new Date(),
    condition: 'new',
    review: 5,
    price: 150,
    discount: 5,
  },
  {
    id: '9',
    title: 'Puma Suede One Piece Straw Hat Luffy',
    description_short:
      'The Puma Suede One Piece Straw Hat Luffy sneaker is a vibrant homage to the beloved protagonist of the iconic anime series, One Piece.',
    description: [
      'Dressed in shades of feather grey and platinum grey, this sneaker captures the spirit of adventure and determination that Luffy embodies. Designed for fans who carry the essence of exploration and the dream of finding their own "One Piece," this edition marries the timeless appeal of Puma Suede with the adventurous heart of the Straw Hat crew.',
      "Luffy, known for his unwavering resolve and charismatic leadership, inspires the design of this sneaker. The color palette, though understated, reflects the simplicity and depth of Luffy's character, offering a versatile look that can accompany fans on their own quests and daily adventures. The sneaker features subtle nods to the One Piece series that resonate with fans, making it a wearable piece of the saga they cherish.",
      'Launched on March 23, 2024',
    ],
    images: {
      local:
        '../../../../assets/image/products/Puma Suede One Piece Straw Hat Luffy.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Puma-Suede-One-Piece-Whitebeard/Images/Puma-Suede-One-Piece-Whitebeard/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1712259045&h=384&q=57',
    },
    size: [
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
    ],
    tag: [{ id: 1, name: 'puma' }],
    color: ['grey'],
    releaseDate: new Date(),
    condition: 'new',
    review: 3,
    price: 119,
    discount: 15,
  },
  {
    id: '10',
    title: 'Jordan 1 Retro High Rare Air Max Orange (GS)',
    description_short: 'Jordan 1 Retro is the best option',
    description: ['A classic with the Jordan 1'],
    images: {
      local:
        '../../../../assets/image/products/Jordan 1 Retro High Rare Air Max Orange (GS).avif',
      number: 1,
      path: 'https://images.stockx.com/360/Air-Jordan-1-Retro-High-Rare-Nike-Air-Max-Orange-GS/Images/Air-Jordan-1-Retro-High-Rare-Nike-Air-Max-Orange-GS/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1626903857&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '44.5',
      '45',
    ],
    tag: [
      { id: 1, name: 'jordan' },
      { id: 2, name: 'retro' },
    ],
    color: ['red', 'white'],
    releaseDate: new Date(),
    condition: 'new',
    review: 4.5,
    price: 95,
  },
  {
    id: '11',
    title: 'Nike Air Max 90 Michigan Navy',
    description_short:
      'The Nike Air Max 90 Michigan Navy comes in a navy, white-varsity maize color scheme.',
    description: [
      'The Michigan Navy Nike Air Max 90 upper is made from a blend of durable and breathable materials, including leather, mesh, and synthetic overlays.',
      'It showcases a noticeable Air Max unit positioned in the heel, ensuring shock absorption and cushioning.',
      'The shoe boasts a lacing system that enables a secure fit tailored to individual preferences.',
    ],
    images: {
      local:
        '../../../../assets/image/products/Nike Air Max 90 Michigan Navy.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Nike-Air-Max-90-Michigan-Navy/Images/Nike-Air-Max-90-Michigan-Navy/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1635166729&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
    ],
    tag: [{ id: 1, name: 'nike' }],
    color: ['black', 'white'],
    releaseDate: new Date(),
    condition: 'used',
    review: 3,
    price: 183,
  },
  {
    id: '12',
    title: 'Nike Kobe 6 Protro Reverse Grinch',
    description_short:
      'Step into the future while honoring a legend with the Nike Kobe 6 Protro Reverse Grinch.',
    description: [
      'This long-awaited sneaker, flips the script on the iconic Grinch colorway.',
      "Boasting a Bright Crimson upper that mirrors the intensity of Kobe's game, this shoe is a standout piece in any collection. The snakeskin-textured upper, a nod to the Black Mamba himself, is complemented by black Swooshes and electrifying Electric Green accents.",
    ],
    images: {
      local:
        '../../../../assets/image/products/Nike Kobe 6 Protro Reverse Grinch.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Nike-Kobe-6-Protro-Reverse-Grinch/Images/Nike-Kobe-6-Protro-Reverse-Grinch/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1701444492&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
    ],
    tag: [{ id: 1, name: 'nike' }],
    color: ['red'],
    releaseDate: new Date(),
    condition: 'used',
    review: 1,
    price: 205,
  },
  {
    id: '13',
    title: "Nike Air Force 1 Low Shadow White Glacier Blue Ghost (Women's)",
    description_short:
      'The Women’s Nike Air Force 1 Shadow White Glacier Blue Ghost carries on the tradition of the bold yet sleek look of the Air Force 1 line.',
    description: [
      'The design incorporates unique and layered wrappings of the Air Force 1 on the heel and the distinct raised borders on the toe cap, logo and eye stay.',
      'The lining continues the color-blocking look with a soft purple tone that contrasts the surrounding collar.',
      'The Women’s Nike Air Force 1 Shadow White Glacier Blue Ghost has a pastel color palette with soft-colored edges attractively bridging across the upper.',
    ],
    images: {
      local:
        "../../../../assets/image/products/Nike Air Force 1 Low Shadow White Glacier Blue Ghost (Women's).avif",
      number: 1,
      path: 'https://images.stockx.com/360/Nike-Air-Force-1-Shadow-White-Glacier-Blue-Ghost-W/Images/Nike-Air-Force-1-Shadow-White-Glacier-Blue-Ghost-W/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1635344410&h=384&q=57',
    },
    size: [
      '35',
      '35.5',
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
    ],
    tag: [{ id: 1, name: 'nike' }],
    color: ['white'],
    releaseDate: new Date(),
    condition: 'used',
    review: 4.5,
    price: 105,
  },
  {
    id: '14',
    title: 'Jordan 5 Retro Olive (2024)',
    description_short:
      'The Jordan 5 Retro Olive (2024) is an updated relaunch of the Jordan 5 Retro Olive that made its debut in 2006.',
    description: [
      'The 2024 version features an upper made of Army Olive suede with mesh peeking through cutouts on the side panels. The plastic eyestays and laces also come in Army Olive. Splashes of Solar Orange provide contrast on the collar, the inside of the tongue, and the midsole. The Jumpman logos stitched across the heel and displayed on the tongue also come in Solar Orange. Other eye-catching features include the jagged design across the midsole, which resembles sharp teeth. Like other Jordan 5 Retro Models, the Olive (2024) version boasts visible Air-sole cushioning in the heel.',
    ],
    images: {
      local:
        '../../../../assets/image/products/Jordan 5 Retro Olive (2024).avif',
      number: 1,
      path: 'https://images.stockx.com/360/Air-Jordan-5-Retro-Olive-2024/Images/Air-Jordan-5-Retro-Olive-2024/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1708716113&h=384&q=57',
    },
    size: [
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '45',
      '45.5',
      '46',
    ],
    tag: [
      { id: 1, name: 'nike' },
      { id: 2, name: 'jordan' },
      { id: 3, name: 'retro' },
    ],
    color: ['green'],
    releaseDate: new Date(),
    condition: 'used',
    review: 5,
    price: 125,
  },
  {
    id: '15',
    title: 'Puma LaMelo Ball LaFrancé Amour For All Time Red',
    description_short: 'Puma nice Edition',
    description: ['Launched on March 5, 2024'],
    images: {
      local:
        '../../../../assets/image/products/Puma LaMelo Ball LaFrancé Amour.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Puma-LaMelo-Ball-LaFrance-Amour-Red/Images/Puma-LaMelo-Ball-LaFrance-Amour-Red/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1715868949&h=384&q=57',
    },
    size: [
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '45',
      '45.5',
      '46',
    ],
    tag: [{ id: 1, name: 'puma' }],
    color: ['purple'],
    releaseDate: new Date(),
    condition: 'used',
    review: 3,
    price: 125,
  },
  {
    id: '16',
    title: 'Puma LaMelo Ball MB.03 Toxic',
    description_short:
      'The Puma LaMelo Ball MB.03 Toxic effortlessly combines style and functionality, taking inspiration from an extraterrestrial realm. The design integrates bold elements such as slime and claw marks, creating a visually aggressive aesthetic.',
    description: [
      'With slime-inspired rubber wrap-ups and an engineered knit upper featuring scratch cutout, the Puma LaMelo Ball MB.03 Toxic showcases a vibrant Purple Glimmer-Green Gecko color combination. The spotlight is on NITROFOAM, a nitrogen-infused foam providing responsive cushioning in a lightweight configuration. The durability and comfort of the shoe are enhanced by the engineered mesh upper and TPU heel counter. A high abrasion, non-slip rubber outsole guarantees excellent traction, and personalized LaMelo Ball branding adds a distinctive touch.',
    ],
    images: {
      local:
        '../../../../assets/image/products/Puma LaMelo Ball MB.03 Toxic.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Puma-LaMelo-Ball-MB03-Toxic/Images/Puma-LaMelo-Ball-MB03-Toxic/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1699460747&h=384&q=57',
    },
    size: [
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '45',
      '45.5',
      '46',
    ],
    tag: [{ id: 1, name: 'puma' }],
    color: ['purple'],
    releaseDate: new Date(),
    condition: 'refurbished',
    review: 4.5,
    price: 71,
  },
  {
    id: '17',
    title: 'Puma LaMelo Ball MB.01 Black Red Blast',
    description_short:
      'The Puma MB01 LaMelo Ball Black Red Blast is a sleek and stylish basketball shoe that is sure to turn heads on and off the court. ',
    description: [
      'The shoe features a black and red colorway that is both bold and eye-catching, making it the perfect choice for players who want to make a statement with their footwear.',
      'The upper of the shoe is made from a combination of synthetic leather and mesh, which provides a comfortable and breathable fit.',
      " The midsole is made from Puma's proprietary ProFoam technology, which offers excellent cushioning and support for the foot.",
    ],
    images: {
      local:
        '../../../../assets/image/products/Puma LaMelo Ball MB.01 Black Red Blast.avif',
      number: 1,
      path: 'https://images.stockx.com/360/Puma-MB01-LaMelo-Ball-Black-Red-Blast/Images/Puma-MB01-LaMelo-Ball-Black-Red-Blast/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1645607492&h=384&q=57',
    },
    size: [
      '36',
      '36.5',
      '37',
      '37.5',
      '38',
      '38.5',
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '45',
      '45.5',
      '46',
    ],
    tag: [{ id: 1, name: 'puma' }],
    color: ['black', 'red'],
    releaseDate: new Date(),
    condition: 'refurbished',
    review: 1.5,
    price: 20,
    discount: 15,
  },
  {
    id: '18',
    title: 'New Balance 9060 Black Castlerock Grey',
    description_short:
      'The New Balance 9060 Black Castlerock Grey was inspired by a 90s model and comes in a grey, black, and red colorway.',
    description: [
      'This Black New Balance 9060 sneaker consists of a black mesh base with monochromatic pigskin suede and leather overlays. The shoe is designed with "N" branding on the side panel, a plush tongue, and flat laces. The model has a CR device at the heel. The design is completed by a chunky, dual-density midsole equipped with ABZORB and SBS cushioning.',
    ],
    images: {
      local:
        '../../../../assets/image/products/New Balance 9060 Black Castlerock Grey.avif',
      number: 1,
      path: 'https://images.stockx.com/360/New-Balance-9060-Black-Castlerock-Grey/Images/New-Balance-9060-Black-Castlerock-Grey/Lv2/img01.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1665037505&h=384&q=57',
    },
    size: [
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '44.5',
      '45',
      '46',
    ],
    tag: [{ id: 1, name: 'new balance' }],
    color: ['black'],
    releaseDate: new Date(),
    condition: 'used',
    review: 5,
    price: 94,
    discount: 5,
  },
  {
    id: '19',
    title: 'New Balance 9060 Black White',
    description_short:
      'The New Balance 9060 Black White arrives in a black-and-white color palette.',
    description: [
      `The New Balance 9060 Black White has a black upper made of synthetic material with black and white embellishments and a white midsole. The black upper is made up of mesh, suede, and synthetic leather. The shoe bears a white "N" logo on the lateral sides and an "NB" logo on the tongue. The midsole is entirely white and incorporates ABZORB's signature cushioning. The shoe's outsole is black and made of rubber for grip and stability.`,
    ],
    images: {
      local:
        '../../../../assets/image/products/New Balance 9060 Black White.avif',
      number: 1,
      path: 'https://images.stockx.com/360/New-Balance-9060-Black-White/Images/New-Balance-9060-Black-White/Lv2/img03.jpg?fm=avif&auto=compress&w=576&dpr=1&updated_at=1679602801&h=384&q=57',
    },
    size: [
      '39',
      '39.5',
      '40',
      '40.5',
      '41',
      '41.5',
      '42',
      '42.5',
      '43',
      '43.5',
      '44',
      '44.5',
      '45',
      '46',
    ],
    tag: [{ id: 1, name: 'new balance' }],
    color: ['black', 'white'],
    releaseDate: new Date(),
    condition: 'refurbished',
    review: 5,
    price: 140,
    discount: 10,
  },
];

export const ProductCardDefault: ProductCard = {
  id: '',
  img: '',
  title: '',
  price: 0,
  review: 0,
  discount: 0,
};

export const ProductAdsDefault: ProductsAds = {
  id: '',
  img: '',
  title: '',
  price: 0,
  discount: 0,
  rows: 1,
  cols: 1,
  image: true,
};

export const ProductCategoriesDefault: ProductCategories[] = [
  'men',
  'women',
  'unisex',
];
